# Generated by Django 4.2.6 on 2023-11-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryagent',
            old_name='blocked',
            new_name='is_blocked',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='food_products',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='deliveryagent',
            name='user',
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
