# Generated by Django 4.2.6 on 2023-11-19 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customer_total_orders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='total_amount_received',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(default='email@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
        ),
    ]
