# Generated by Django 4.2.6 on 2023-11-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_customer_user_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryagent',
            name='otp',
        ),
        migrations.AddField(
            model_name='order',
            name='otp',
            field=models.IntegerField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
